In [1]:
import pandas as pd

df = pd.read_csv("malaysia_house_price_data_2025.csv")

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (2000, 8)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Township      2000 non-null   object
 1   Area          2000 non-null   object
 2   State         2000 non-null   object
 3   Tenure        2000 non-null   object
 4   Type          2000 non-null   object
 5   Median_Price  2000 non-null   float64
 6   Median_PSF    2000 non-null   float64
 7   Transactions  2000 non-null   int64
dtypes: float64(2), int64(1), object(5)
memory usage: 125.1+ KB

In [3]:
df[['Median_Price', 'Median_PSF', 'Transactions']].describe().round(2)

       Median_Price  Median_PSF  Transactions
count       2000.00     2000.00       2000.00
mean      490685.41      328.86         28.09
std       468632.21      193.28         37.70
min        27049.00       38.00         10.00
25%       269950.00      201.00         12.00
50%       390000.00      293.00         16.00
75%       573500.00      412.00         28.00
max     11420500.00     3017.00        593.00

In [4]:
df.isnull().sum()

Township        0
Area            0
State           0
Tenure          0
Type            0
Median_Price    0
Median_PSF      0
Transactions    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,Tasek Gelugor,Penang,Freehold,Terrace House,331800.0,304.0,593
1,BANDAR PUTRA,Kulai,Johor,Freehold,"Cluster House, Terrace House",590900.0,322.0,519
2,TAMAN LAGENDA TROPIKA TAPAH,Chenderiang,Perak,Freehold,Terrace House,229954.0,130.0,414
3,SCIENTEX JASIN MUTIARA,Bemban,Melaka,Freehold,Terrace House,255600.0,218.0,391
4,TAMAN LAGENDA AMAN,Tapah,Perak,Leasehold,Terrace House,219300.0,168.0,363

In [7]:
display((df[['Median_Price', 'Median_PSF', 'Transactions']] <= 0).sum())

Median_Price    0
Median_PSF      0
Transactions    0
dtype: int64

In [8]:
categorical_columns = ['Township', 'Area', 'State', 'Tenure', 'Type']

for col in categorical_columns:
    df[col] = df[col].astype(str).str.strip().str.upper()

print("Categorical values standardized")

Categorical values standardized

In [9]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,TASEK GELUGOR,PENANG,FREEHOLD,TERRACE HOUSE,331800.0,304.0,593
1,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,"CLUSTER HOUSE, TERRACE HOUSE",590900.0,322.0,519
2,TAMAN LAGENDA TROPIKA TAPAH,CHENDERIANG,PERAK,FREEHOLD,TERRACE HOUSE,229954.0,130.0,414
3,SCIENTEX JASIN MUTIARA,BEMBAN,MELAKA,FREEHOLD,TERRACE HOUSE,255600.0,218.0,391
4,TAMAN LAGENDA AMAN,TAPAH,PERAK,LEASEHOLD,TERRACE HOUSE,219300.0,168.0,363

In [10]:
for col in categorical_columns:
    print(col)
    print("Number of unique values:", df[col].nunique())
    print("================================\n")

Township
Number of unique values: 1917
================================

Area
Number of unique values: 303
================================

State
Number of unique values: 16
================================

Tenure
Number of unique values: 4
================================

Type
Number of unique values: 46
================================

In [11]:
multiple_area = df['Area'].str.contains(',', regex=False)
print("Records with multiple area values:", multiple_area.sum())

Records with multiple area values: 0

In [12]:
multiple_state = df['State'].str.contains(',', regex=False)
print("Records with multiple state values:", multiple_state.sum())

Records with multiple state values: 0

In [13]:
multiple_tenure = df['Tenure'].astype(str).str.contains(',', regex=False)
print("Records with multiple tenure values:", multiple_tenure.sum())

Records with multiple tenure values: 58

In [14]:
tenure_combinations = df.loc[multiple_tenure, 'Tenure'].value_counts()
print(tenure_combinations)

Tenure
FREEHOLD, LEASEHOLD    31
LEASEHOLD, FREEHOLD    27
Name: count, dtype: int64

In [15]:
df = df[~multiple_tenure].copy()
print("Remove multiple-tenure records")
print("Dataset shape after remove multiple-tenure records:", df.shape)
print("Remaining multiple-tenure records:", df['Tenure'].astype(str).str.contains(',', regex=False).sum())

Remove multiple-tenure records
Dataset shape after remove multiple-tenure records: (1942, 8)
Remaining multiple-tenure records: 0

In [16]:
multiple_type = df['Type'].str.contains(',', regex=False)
print("Records with multiple type values:", multiple_type.sum())

Records with multiple type values: 350

In [17]:
type_combinations = df.loc[multiple_type, 'Type'].value_counts()
print(type_combinations)

Type
TERRACE HOUSE, SEMI D                       97
SEMI D, TERRACE HOUSE                       80
TERRACE HOUSE, CLUSTER HOUSE                31
CLUSTER HOUSE, TERRACE HOUSE                22
TERRACE HOUSE, BUNGALOW                     21
BUNGALOW, TERRACE HOUSE                     18
BUNGALOW, SEMI D                            13
TERRACE HOUSE, TOWN HOUSE                    8
SEMI D, BUNGALOW                             8
TOWN HOUSE, TERRACE HOUSE                    7
CLUSTER HOUSE, SEMI D                        6
SEMI D, CLUSTER HOUSE                        4
CLUSTER HOUSE, TERRACE HOUSE, SEMI D         3
BUNGALOW, TERRACE HOUSE, SEMI D              3
TERRACE HOUSE, SEMI D, BUNGALOW              3
SEMI D, TOWN HOUSE, TERRACE HOUSE            2
FLAT, APARTMENT                              2
TERRACE HOUSE, BUNGALOW, SEMI D              2
TERRACE HOUSE, SEMI D, TOWN HOUSE            2
SEMI D, TERRACE HOUSE, BUNGALOW              2
BUNGALOW, TOWN HOUSE                         1
SEMI D, CLUSTER HOUSE, BUNGALOW              1
SEMI D, TERRACE HOUSE, CLUSTER HOUSE         1
TOWN HOUSE, TERRACE HOUSE, SEMI D            1
FLAT, CONDOMINIUM                            1
TOWN HOUSE, BUNGALOW, TERRACE HOUSE          1
APARTMENT, FLAT                              1
TOWN HOUSE, SEMI D                           1
SEMI D, BUNGALOW, TERRACE HOUSE              1
TOWN HOUSE, SEMI D, TERRACE HOUSE            1
CONDOMINIUM, SERVICE RESIDENCE               1
CLUSTER HOUSE, BUNGALOW                      1
BUNGALOW, SEMI D, TERRACE HOUSE              1
SEMI D, TERRACE HOUSE, TOWN HOUSE            1
CLUSTER HOUSE, TOWN HOUSE, TERRACE HOUSE     1
SEMI D, TOWN HOUSE                           1
Name: count, dtype: int64

In [18]:
df['Type_Standardized'] = df['Type'].apply(lambda x: ', '.join(sorted([t.strip() for t in x.split(',')])))
type_standardized_combination = df.loc[multiple_type, 'Type_Standardized'].value_counts()
print(type_standardized_combination)

Type_Standardized
SEMI D, TERRACE HOUSE                       177
CLUSTER HOUSE, TERRACE HOUSE                 53
BUNGALOW, TERRACE HOUSE                      39
BUNGALOW, SEMI D                             21
TERRACE HOUSE, TOWN HOUSE                    15
BUNGALOW, SEMI D, TERRACE HOUSE              12
CLUSTER HOUSE, SEMI D                        10
SEMI D, TERRACE HOUSE, TOWN HOUSE             7
CLUSTER HOUSE, SEMI D, TERRACE HOUSE          4
APARTMENT, FLAT                               3
SEMI D, TOWN HOUSE                            2
BUNGALOW, CLUSTER HOUSE, SEMI D               1
CONDOMINIUM, FLAT                             1
BUNGALOW, TOWN HOUSE                          1
BUNGALOW, TERRACE HOUSE, TOWN HOUSE           1
CONDOMINIUM, SERVICE RESIDENCE                1
BUNGALOW, CLUSTER HOUSE                       1
CLUSTER HOUSE, TERRACE HOUSE, TOWN HOUSE      1
Name: count, dtype: int64

In [19]:
df['Type_Standardized'] = (df['Type_Standardized'].str.split(', '))
df = df.explode('Type_Standardized',ignore_index=True)
df['Type'] = df['Type_Standardized']
df.drop(columns=['Type_Standardized'],inplace=True)
print("Type splitting completed")
print("Remaining multiple type records:",df['Type'].str.contains(',', regex=False).sum())
print("New dataset shape:", df.shape)

Type splitting completed
Remaining multiple type records: 0
New dataset shape: (2318, 8)

In [20]:
print(df['Type'].value_counts())

Type
TERRACE HOUSE        1226
SEMI D                277
APARTMENT             199
CONDOMINIUM           169
FLAT                  135
SERVICE RESIDENCE      96
CLUSTER HOUSE          93
BUNGALOW               89
TOWN HOUSE             34
Name: count, dtype: int64

In [21]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,TASEK GELUGOR,PENANG,FREEHOLD,TERRACE HOUSE,331800.0,304.0,593
1,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,CLUSTER HOUSE,590900.0,322.0,519
2,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,TERRACE HOUSE,590900.0,322.0,519
3,TAMAN LAGENDA TROPIKA TAPAH,CHENDERIANG,PERAK,FREEHOLD,TERRACE HOUSE,229954.0,130.0,414
4,SCIENTEX JASIN MUTIARA,BEMBAN,MELAKA,FREEHOLD,TERRACE HOUSE,255600.0,218.0,391

In [22]:
numerical_columns  = ['Median_Price', 'Median_PSF']
for col in numerical_columns:
    Q1 = df.groupby(['Type'])[col].transform('quantile', 0.25)
    Q3 = df.groupby(['Type'])[col].transform('quantile', 0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    count_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    lower_3 = Q1 - 3.0 * IQR
    upper_3 = Q3 + 3.0 * IQR
    count_outliers_3 = df[(df[col] < lower_3) | (df[col] > upper_3)]

    print(col)
    print("Number of outliers (1.5 x IQR):", len(count_outliers))
    print("Number of outliers (3.0 x IQR):", len(count_outliers_3))
    print("=======================================\n")

Median_Price
Number of outliers (1.5 x IQR): 127
Number of outliers (3.0 x IQR): 52
=======================================

Median_PSF
Number of outliers (1.5 x IQR): 51
Number of outliers (3.0 x IQR): 9
=======================================

In [23]:
cleaned_df = df.copy()

for col in numerical_columns:

    Q1 = cleaned_df.groupby(['Type'])[col].transform('quantile', 0.25)
    Q3 = cleaned_df.groupby(['Type'])[col].transform('quantile', 0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 3 * IQR
    upper_bound = Q3 + 3 * IQR

    lower_outliers = (cleaned_df[col] < lower_bound).sum()
    upper_outliers = (cleaned_df[col] > upper_bound).sum()

    cleaned_df[col] = cleaned_df[col].clip(
        lower=lower_bound,
        upper=upper_bound
    )

    print(col)
    print("Lower outliers capped:", lower_outliers)
    print("Upper outliers capped:", upper_outliers)
    print("====================================\n")

Median_Price
Lower outliers capped: 0
Upper outliers capped: 52
====================================

Median_PSF
Lower outliers capped: 0
Upper outliers capped: 9
====================================

In [24]:
display(cleaned_df[['Median_Price', 'Median_PSF', 'Transactions']].describe().round(2))

       Median_Price  Median_PSF  Transactions
count       2318.00     2318.00       2318.00
mean      492974.45      324.65         29.05
std       348183.58      180.22         39.46
min        27049.00       38.00         10.00
25%       275450.00      197.00         12.00
50%       400000.00      289.00         17.00
75%       600000.00      413.75         29.00
max      3600000.00     1815.00        593.00

In [25]:
cleaned_df.to_csv('malaysia_house_price_data_2025_cleaned.csv', index=False)
print("Cleaned dataset exported to 'malaysia_house_price_data_2025_cleaned.csv'")

Cleaned dataset exported to 'malaysia_house_price_data_2025_cleaned.csv'

In [26]:
df_recheck = pd.read_csv('malaysia_house_price_data_2025_cleaned.csv')

print("Dataset loaded successfully")

print("\nShape:", df_recheck.shape)
print("\nTotal Missing Values:", df_recheck.isnull().sum().sum())
print("\nDuplicate Rows:", df_recheck.duplicated().sum())
print("\nMaximum Values:")
print(df_recheck[['Median_Price', 'Median_PSF', 'Transactions']].max())
print("\nMinimum Values:")
print(df_recheck[['Median_Price', 'Median_PSF', 'Transactions']].min())
print()
for col in categorical_columns:
    print(col)
    print("Number of unique values:", df_recheck[col].nunique())
    print("Blank strings:", (df_recheck[col].astype(str).str.strip() == '').sum())
    print("================================\n")

Dataset loaded successfully

Shape: (2318, 8)

Total Missing Values: 0

Duplicate Rows: 0

Maximum Values:
Median_Price    3600000.0
Median_PSF         1815.0
Transactions        593.0
dtype: float64

Minimum Values:
Median_Price    27049.0
Median_PSF         38.0
Transactions       10.0
dtype: float64

Township
Number of unique values: 1867
Blank strings: 0
================================

Area
Number of unique values: 299
Blank strings: 0
================================

State
Number of unique values: 16
Blank strings: 0
================================

Tenure
Number of unique values: 2
Blank strings: 0
================================

Type
Number of unique values: 9
Blank strings: 0
================================